FROM python:3.5-alpine

#FROM lsiobase/alpine:3.5

# freenas Corral labels
#LABEL org.freenas.expose-ports-at-host="true" \
#      org.freenas.autostart="true" \
#      org.freenas.port-mappings="3539:3539/tcp" \
#      org.freenas.volumes="[{ \"name\": \"/flexget\", \"descr\": \"flexget storage space\" }]"

#FROM python:3.5-alpine
#VOLUME /flexget
#RUN pip install transmissionrpc && pip install flexget
#EXPOSE 3539
#WORKDIR /flexget
#CMD rm -f /flexget/.config-lock && flexget daemon start