#!/usr/bin/with-contenv bash

# copy config
[[ ! -f /flexget/config.yml ]] && cp \
	/defaults/config.yml /flexget/config.yml

# permissions
chown abc:abc \
	/flexget/config.yml 

flexget -c /flexget/config.yml daemon start -d 